package chipyard.fpga.nm37

import chisel3._
import chisel3.experimental.Analog
import chisel3.util._
import freechips.rocketchip.amba.axi4._
import freechips.rocketchip.diplomacy.{AddressSet, RegionType, TransferSizes}
import freechips.rocketchip.util.ElaborationArtefacts
import org.chipsalliance.cde.config.Parameters
import freechips.rocketchip.prci.{ClockSinkNode, ClockSinkParameters, ClockSourceNode}
import freechips.rocketchip.resources.SimpleDevice
import org.chipsalliance.diplomacy.lazymodule._
import freechips.rocketchip.util.BooleanToAugmentedBoolean

import sifive.fpgashells.shell.IOPin

/*
 * DDR4 MIG (ddr4:2.2) controller for the NM37 board (VU37P, ICT).
 *
 * Board facts (from /home/zhangsi/nexst/shell/nm37):
 *  - DDR4 SODIMM: MTA16ATF2G64HZ-2G3 (2GB, x64), TimePeriod 938, CL15
 *  - MIG AXI: 512-bit data, shared between the host (XDMA DMA) and the FSA
 *  - ui_clk ~= 300MHz (generated by the MIG itself)
 *  - sys clock: differential 100MHz on BH42/BJ42, consumed No_Buffer
 *    (fed from the harness sys_clock IBUFDS output)
 *  - Port names of the generated IP must match the nexst top.xdc names
 */
class XilinxDDR4Pads extends Bundle {
  // address/command pins (outputs of the FPGA)
  val c0_ddr4_act_n   = Output(Bool())
  val c0_ddr4_adr     = Output(Bits(17.W))
  val c0_ddr4_ba      = Output(Bits(2.W))
  val c0_ddr4_bg      = Output(Bits(2.W))
  val c0_ddr4_ck_t    = Output(Bits(2.W))
  val c0_ddr4_ck_c    = Output(Bits(2.W))
  val c0_ddr4_cke     = Output(Bits(2.W))
  val c0_ddr4_cs_n    = Output(Bits(2.W))
  val c0_ddr4_odt     = Output(Bits(2.W))
  val c0_ddr4_reset_n = Output(Bool())
  // bidirectional pins
  val c0_ddr4_dq      = Analog(64.W)
  val c0_ddr4_dqs_t   = Analog(8.W)
  val c0_ddr4_dqs_c   = Analog(8.W)
  val c0_ddr4_dm_n    = Analog(8.W)
}

// DDR4 pin locations on the NM37, LSB first (from nexst nm37 top.xdc)
object NM37DDR4Pins {
  val act_n   = Seq("BP44")
  val adr     = Seq("BK45", "BL45", "BL43", "BN44", "BP46", "BL46", "BH46", "BJ43",
                    "BN46", "BN45", "BM42", "BM45", "BH44", "BL42", "BH41", "BK43", "BJ41")
  val ba      = Seq("BK41", "BG43")
  val bg      = Seq("BK46", "BJ44")
  val ck_t    = Seq("BN42", "BN47")
  val ck_c    = Seq("BP42", "BP47")
  val cke     = Seq("BM47", "BJ46")
  val cs_n    = Seq("BG42", "BE41")
  val odt     = Seq("BF41", "BH45")
  val reset_n = Seq("BL47")
  val dm_n    = Seq("BG48", "BJ52", "BK48", "BP48", "BH32", "BM34", "BM28", "BG29")
  val dq      = Seq(
    "BE49", "BE51", "BF50", "BF52", "BE50", "BD51", "BG50", "BF51",
    "BE54", "BG52", "BG54", "BK54", "BE53", "BG53", "BK53", "BH52",
    "BH51", "BJ51", "BH50", "BJ49", "BK50", "BK51", "BH49", "BJ48",
    "BL53", "BL52", "BN50", "BM48", "BL51", "BM52", "BN51", "BN49",
    "BF35", "BH35", "BJ33", "BG35", "BF36", "BH34", "BJ34", "BG34",
    "BN34", "BL33", "BL31", "BK31", "BP34", "BM33", "BL32", "BK33",
    "BP32", "BN31", "BP28", "BL30", "BP31", "BN32", "BP29", "BM30",
    "BH31", "BH29", "BF31", "BF32", "BH30", "BJ31", "BG32", "BF33")
  val dqs_t   = Seq("BF47", "BH54", "BH47", "BM49", "BK34", "BL35", "BN29", "BJ29")
  val dqs_c   = Seq("BF48", "BJ54", "BJ47", "BM50", "BK35", "BM35", "BN30", "BK30")

  // Bind the pin locations of a top-level DDR4 pads bundle (LSB first)
  def bind(xdc: sifive.fpgashells.shell.xilinx.XDC, pads: XilinxDDR4Pads): Unit = {
    def bindField(x: Data, pins: Seq[String]) {
      (IOPin.of(x) zip pins) foreach { case (io, pin) => xdc.addPackagePin(io, pin) }
    }
    bindField(pads.c0_ddr4_act_n,   act_n)
    bindField(pads.c0_ddr4_adr,     adr)
    bindField(pads.c0_ddr4_ba,      ba)
    bindField(pads.c0_ddr4_bg,      bg)
    bindField(pads.c0_ddr4_ck_t,    ck_t)
    bindField(pads.c0_ddr4_ck_c,    ck_c)
    bindField(pads.c0_ddr4_cke,     cke)
    bindField(pads.c0_ddr4_cs_n,    cs_n)
    bindField(pads.c0_ddr4_odt,     odt)
    bindField(pads.c0_ddr4_reset_n, reset_n)
    bindField(pads.c0_ddr4_dq,      dq)
    bindField(pads.c0_ddr4_dqs_t,   dqs_t)
    bindField(pads.c0_ddr4_dqs_c,   dqs_c)
    bindField(pads.c0_ddr4_dm_n,    dm_n)
  }
}

class XilinxDDR4MIGIO(val axiParams: AXI4BundleParameters) extends Bundle {
  // DDR4 memory pins
  val c0_ddr4_act_n   = Output(Bool())
  val c0_ddr4_adr     = Output(Bits(17.W))
  val c0_ddr4_ba      = Output(Bits(2.W))
  val c0_ddr4_bg      = Output(Bits(2.W))
  val c0_ddr4_ck_t    = Output(Bits(2.W))
  val c0_ddr4_ck_c    = Output(Bits(2.W))
  val c0_ddr4_cke     = Output(Bits(2.W))
  val c0_ddr4_cs_n    = Output(Bits(2.W))
  val c0_ddr4_odt     = Output(Bits(2.W))
  val c0_ddr4_reset_n = Output(Bool())
  val c0_ddr4_dq      = Analog(64.W)
  val c0_ddr4_dqs_t   = Analog(8.W)
  val c0_ddr4_dqs_c   = Analog(8.W)
  val c0_ddr4_dm_n    = Analog(8.W)

  // system clock (No_Buffer: driven by the harness IBUFDS output) and reset
  val c0_sys_clk_i              = Input(Bool())
  val sys_rst                   = Input(Bool())
  // user interface
  val c0_ddr4_ui_clk            = Output(Clock())
  val c0_ddr4_ui_clk_sync_rst   = Output(Bool())
  val c0_init_calib_complete    = Output(Bool())
  val c0_ddr4_aresetn           = Input(Bool())

  // AXI4 slave interface (full-width bursts only). The ID width follows the
  // diplomacy negotiation (an AXI4Xbar with N masters needs log2(extra
  // masters) more ID bits than the widest master, e.g. 5 for XDMA(4) + FSA),
  // and the MIG IP is configured to match, mirroring the U280 HBM approach.
  val c0_ddr4_s_axi_awid      = Input(Bits(axiParams.idBits.W))
  val c0_ddr4_s_axi_awaddr    = Input(Bits(34.W))
  val c0_ddr4_s_axi_awlen     = Input(Bits(8.W))
  val c0_ddr4_s_axi_awsize    = Input(Bits(3.W))
  val c0_ddr4_s_axi_awburst   = Input(Bits(2.W))
  val c0_ddr4_s_axi_awlock    = Input(Bits(1.W))
  val c0_ddr4_s_axi_awcache   = Input(Bits(4.W))
  val c0_ddr4_s_axi_awprot    = Input(Bits(3.W))
  val c0_ddr4_s_axi_awqos     = Input(Bits(4.W))
  val c0_ddr4_s_axi_awvalid   = Input(Bool())
  val c0_ddr4_s_axi_awready   = Output(Bool())
  val c0_ddr4_s_axi_wdata     = Input(Bits(512.W))
  val c0_ddr4_s_axi_wstrb     = Input(Bits(64.W))
  val c0_ddr4_s_axi_wlast     = Input(Bool())
  val c0_ddr4_s_axi_wvalid    = Input(Bool())
  val c0_ddr4_s_axi_wready    = Output(Bool())
  val c0_ddr4_s_axi_bid       = Output(Bits(axiParams.idBits.W))
  val c0_ddr4_s_axi_bresp     = Output(Bits(2.W))
  val c0_ddr4_s_axi_bvalid    = Output(Bool())
  val c0_ddr4_s_axi_bready    = Input(Bool())
  val c0_ddr4_s_axi_arid      = Input(Bits(axiParams.idBits.W))
  val c0_ddr4_s_axi_araddr    = Input(Bits(34.W))
  val c0_ddr4_s_axi_arlen     = Input(Bits(8.W))
  val c0_ddr4_s_axi_arsize    = Input(Bits(3.W))
  val c0_ddr4_s_axi_arburst   = Input(Bits(2.W))
  val c0_ddr4_s_axi_arlock    = Input(Bits(1.W))
  val c0_ddr4_s_axi_arcache   = Input(Bits(4.W))
  val c0_ddr4_s_axi_arprot    = Input(Bits(3.W))
  val c0_ddr4_s_axi_arqos     = Input(Bits(4.W))
  val c0_ddr4_s_axi_arvalid   = Input(Bool())
  val c0_ddr4_s_axi_arready   = Output(Bool())
  val c0_ddr4_s_axi_rid       = Output(Bits(axiParams.idBits.W))
  val c0_ddr4_s_axi_rdata     = Output(Bits(512.W))
  val c0_ddr4_s_axi_rresp     = Output(Bits(2.W))
  val c0_ddr4_s_axi_rlast     = Output(Bool())
  val c0_ddr4_s_axi_rvalid    = Output(Bool())
  val c0_ddr4_s_axi_rready    = Input(Bool())
}

class XilinxDDR4MIG
(
  axiParams: AXI4BundleParameters,
  override val desiredName: String
) extends BlackBox {
  // The diplomacy edge (xbar output) may legitimately be narrower than the
  // fixed IP port widths above; widths are adapted at the connection site.
  val io = IO(new XilinxDDR4MIGIO(axiParams))

  ElaborationArtefacts.add(s"$desiredName.vivado.tcl",
    s"""
       |create_ip -vendor xilinx.com -library ip -version 2.2 -name ddr4 -module_name $desiredName -dir $$ipdir -force
       |set_property -dict [list \\
       |    CONFIG.C0.DDR4_isCustom          {false} \\
       |    CONFIG.C0.DDR4_InputClockPeriod  {10005} \\
       |    CONFIG.C0.DDR4_TimePeriod        {938} \\
       |    CONFIG.C0.DDR4_MemoryType        {SODIMMs} \\
       |    CONFIG.C0.DDR4_MemoryPart        {MTA16ATF2G64HZ-2G3} \\
       |    CONFIG.C0.DDR4_AxiAddressWidth   {34} \\
       |    CONFIG.C0.DDR4_AxiDataWidth      {512} \\
       |    CONFIG.C0.DDR4_AxiIDWidth        {${axiParams.idBits}} \\
       |    CONFIG.C0.DDR4_DataWidth         {64} \\
       |    CONFIG.C0.DDR4_CasLatency        {15} \\
       |    CONFIG.C0.DDR4_AxiNarrowBurst    {false} \\
       |    CONFIG.System_Clock              {No_Buffer} \\
       |] [get_ips $desiredName]
       |""".stripMargin)
}

class LazyXilinxDDR4Controller
(
  moduleNamePrefix: String,
)(implicit p: Parameters) extends LazyModule {
  // 2GB SODIMM at address 0x0, 512-bit AXI, full-width bursts of up to 512B
  val node = AXI4SlaveNode(Seq(AXI4SlavePortParameters(
    Seq(AXI4SlaveParameters(
      address = Seq(AddressSet(0x00000000L, 0x7FFFFFFFL)),
      resources = new SimpleDevice("nm37-ddr4", Seq()).reg("mem"),
      regionType = RegionType.UNCACHED,
      executable = true,
      supportsRead = TransferSizes(64, 512),
      supportsWrite = TransferSizes(64, 512),
      interleavedId = Some(0),
    )),
    beatBytes = 64,
    requestKeys = Seq(),
    responseFields = Nil,
  )))

  // 100MHz differential system clock (consumed post-IBUFDS, No_Buffer)
  val sysClkNode = ClockSinkNode(Seq(ClockSinkParameters()))
  // ui_clk (~300MHz) generated by the MIG itself, exported as a clock source
  val uiClkSource = ClockSourceNode(freqMHz = 300)

  lazy val module = new Impl(this)
  class Impl(wrapper: LazyXilinxDDR4Controller) extends LazyRawModuleImp(wrapper) {
    val (in, edge) = node.in.head
    require(edge.bundle.dataBits == 512,
      s"DDR4 MIG requires a 512-bit bus at the FSA memory side, got ${edge.bundle.dataBits}")
    require(edge.bundle.idBits >= 1 && edge.bundle.idBits <= 16,
      s"DDR4 MIG AXI ID width must be 1..16, got ${edge.bundle.idBits}")
    require(edge.bundle.responseFields.isEmpty,
      "DDR4 MIG path must not carry response user fields")

    val mig = Module(new XilinxDDR4MIG(edge.bundle, moduleNamePrefix + "xilinx_ddr4"))
    val pads = IO(new XilinxDDR4Pads)
    pads.suggestName(s"${moduleNamePrefix}ddr4_pads")

    val sysClock = sysClkNode.in.head._1.clock
    val sysReset = sysClkNode.in.head._1.reset

    // system clock and reset
    mig.io.c0_sys_clk_i := sysClock.asUInt
    mig.io.sys_rst := sysReset.asBool

    // export ui_clk as a clock source (reset = the MIG's own synced reset)
    val (ui, _) = uiClkSource.out.head
    ui.clock := mig.io.c0_ddr4_ui_clk
    ui.reset := mig.io.c0_ddr4_ui_clk_sync_rst

    // AXI reset: hold off AXI traffic until the MIG has calibrated
    mig.io.c0_ddr4_aresetn := !(mig.io.c0_ddr4_ui_clk_sync_rst || !mig.io.c0_init_calib_complete)

    // drive the AXI slave port
    mig.io.c0_ddr4_s_axi_awid := in.aw.bits.id
    mig.io.c0_ddr4_s_axi_awaddr := in.aw.bits.addr
    mig.io.c0_ddr4_s_axi_awlen := in.aw.bits.len
    mig.io.c0_ddr4_s_axi_awsize := in.aw.bits.size
    mig.io.c0_ddr4_s_axi_awburst := in.aw.bits.burst
    mig.io.c0_ddr4_s_axi_awlock := in.aw.bits.lock
    mig.io.c0_ddr4_s_axi_awcache := in.aw.bits.cache
    mig.io.c0_ddr4_s_axi_awprot := in.aw.bits.prot
    mig.io.c0_ddr4_s_axi_awqos := in.aw.bits.qos
    mig.io.c0_ddr4_s_axi_awvalid := in.aw.valid
    in.aw.ready := mig.io.c0_ddr4_s_axi_awready

    mig.io.c0_ddr4_s_axi_wdata := in.w.bits.data
    mig.io.c0_ddr4_s_axi_wstrb := in.w.bits.strb
    mig.io.c0_ddr4_s_axi_wlast := in.w.bits.last
    mig.io.c0_ddr4_s_axi_wvalid := in.w.valid
    in.w.ready := mig.io.c0_ddr4_s_axi_wready

    in.b.bits.id := mig.io.c0_ddr4_s_axi_bid
    in.b.bits.resp := mig.io.c0_ddr4_s_axi_bresp
    in.b.valid := mig.io.c0_ddr4_s_axi_bvalid
    mig.io.c0_ddr4_s_axi_bready := in.b.ready

    mig.io.c0_ddr4_s_axi_arid := in.ar.bits.id
    mig.io.c0_ddr4_s_axi_araddr := in.ar.bits.addr
    mig.io.c0_ddr4_s_axi_arlen := in.ar.bits.len
    mig.io.c0_ddr4_s_axi_arsize := in.ar.bits.size
    mig.io.c0_ddr4_s_axi_arburst := in.ar.bits.burst
    mig.io.c0_ddr4_s_axi_arlock := in.ar.bits.lock
    mig.io.c0_ddr4_s_axi_arcache := in.ar.bits.cache
    mig.io.c0_ddr4_s_axi_arprot := in.ar.bits.prot
    mig.io.c0_ddr4_s_axi_arqos := in.ar.bits.qos
    mig.io.c0_ddr4_s_axi_arvalid := in.ar.valid
    in.ar.ready := mig.io.c0_ddr4_s_axi_arready

    in.r.bits.id := mig.io.c0_ddr4_s_axi_rid
    in.r.bits.data := mig.io.c0_ddr4_s_axi_rdata
    in.r.bits.resp := mig.io.c0_ddr4_s_axi_rresp
    in.r.bits.last := mig.io.c0_ddr4_s_axi_rlast
    in.r.valid := mig.io.c0_ddr4_s_axi_rvalid
    mig.io.c0_ddr4_s_axi_rready := in.r.ready

    // top-level DDR4 pins
    pads.c0_ddr4_act_n   := mig.io.c0_ddr4_act_n
    pads.c0_ddr4_adr     := mig.io.c0_ddr4_adr
    pads.c0_ddr4_ba      := mig.io.c0_ddr4_ba
    pads.c0_ddr4_bg      := mig.io.c0_ddr4_bg
    pads.c0_ddr4_ck_t    := mig.io.c0_ddr4_ck_t
    pads.c0_ddr4_ck_c    := mig.io.c0_ddr4_ck_c
    pads.c0_ddr4_cke     := mig.io.c0_ddr4_cke
    pads.c0_ddr4_cs_n    := mig.io.c0_ddr4_cs_n
    pads.c0_ddr4_odt     := mig.io.c0_ddr4_odt
    pads.c0_ddr4_reset_n := mig.io.c0_ddr4_reset_n
    chisel3.experimental.attach(pads.c0_ddr4_dq,    mig.io.c0_ddr4_dq)
    chisel3.experimental.attach(pads.c0_ddr4_dqs_t, mig.io.c0_ddr4_dqs_t)
    chisel3.experimental.attach(pads.c0_ddr4_dqs_c, mig.io.c0_ddr4_dqs_c)
    chisel3.experimental.attach(pads.c0_ddr4_dm_n,  mig.io.c0_ddr4_dm_n)
  }

  // Accessor for the harness top level to bulk-connect its own DDR4 IO onto
  // this module's pads (the Analog fields become top-level inout ports).
  def padsIO: XilinxDDR4Pads = module.pads
}
